# Cloud Build configuration for production deployments (main branch)
steps:
  # Install dependencies
  - name: 'node'
    entrypoint: 'npm'
    args:
      - 'ci'

  # Run tests (uncomment when tests are added)
  # - name: 'node'
  #   entrypoint: 'npm'
  #   args:
  #     - 'test'

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/l0002:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/l0002:latest'
      - '.'

  # Push image to Container Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/l0002'
    id: Push

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - deploy
      - l0002
      - '--platform=managed'
      - '--image=gcr.io/$PROJECT_ID/l0002:$COMMIT_SHA'
      - >-
        --labels=commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,branch=$BRANCH_NAME
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
      - '--port=50002'
      - '--set-env-vars=AUTH_URL=$_AUTH_URL,NODE_ENV=production'
      - '--allow-unauthenticated'
      - '--min-instances=$_MIN_INSTANCES'
      - '--max-instances=$_MAX_INSTANCES'
      - '--memory=$_MEMORY'
    id: Deploy
    entrypoint: gcloud

images:
  - 'gcr.io/$PROJECT_ID/l0002:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/l0002:latest'

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _DEPLOY_REGION: us-central1
  _AUTH_URL: https://auth.graffiticode.org
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '100'
  _MEMORY: '512Mi'

tags:
  - l0002
  - production